coralogix/data_source_coralogix_alert.go, coralogix/resource_coralogix_alert.go, docs/resources/rule.md
* Fixed Alert API
* Added example of the documentation to the Rule.
=> Alert API fix

coralogix/data_source_coralogix_alert.go, coralogix/helpers.go, coralogix/provider.go, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_rule.go, docs/data-sources/alert.md, docs/resources/alert.md
1. implemented the ratio alert type and the ratio block. 
2. fixes and cleaning to function alert resource read, create, and flatteners. 
3. updated the alert docs
4. updated the data source alert.
=> Alert condition validation

coralogix/data_source_coralogix_alert.go, coralogix/helpers.go, coralogix/resource_coralogix_alert.go, docs/resources/alert.md
1. added key group_by_array
2. deprecated group_by (still has support)
3. added values validation
4. added logic to handle use of group_by.
5.updated docs.
=> added support for multiple group_bys

coralogix/helpers.go, coralogix/resource_coralogix_alert.go
- fixed a bug in alert update that didnt update when group_by were removed
=> fix: allow condition less_than to have group_by

coralogix/data_source_coralogix_alert.go, coralogix/helpers.go, coralogix/resource_coralogix_alert.go
- changed from typeSet to typeList to maintain the array order.
=> fix: group_by_array order changing.

coralogix/data_source_coralogix_alert.go, coralogix/helpers.go, coralogix/resource_coralogix_alert.go
- fixed the ratio field from the api.
- changed groupby from typeSet to typeList.
=> fix: ratio alert groupby.

coralogix/helpers.go, coralogix/resource_coralogix_alert.go
- made it explicit how to handle fields under log_filter.
- added a check for when alertsList is nil but no error.
=> fix: alert flatten helper func.

README.md, coralogix/resource_coralogix_alert_test.go, docs/index.md, docs/resources/alert.md, docs/resources/data_set.md, docs/resources/rules_group.md, examples/alert/main.tf, examples/rules_group/main.tf
=> Documentation

coralogix/resource_coralogix_rules_group.go, coralogix/resource_coralogix_rules_group_test.go, docs/resources/enrichment.md, docs/resources/rules_group.md, examples/rules_group/main.tf
Adding an option to decide  the order of rule-group within the other rule-groups
=> Adding rule group order option

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, coralogix/resource_coralogix_rules_group.go, docs/data-sources/rules_group.md, docs/resources/alert.md, docs/resources/rules_group.md, examples/alert/main.tf, known-issues.md
changing arithmetic_operator_modifier to optional and fixing metric-alert and rule-groups documentation
=> changing arithmetic_operator_modifier to optional and fixing documentation

coralogix/resource_coralogix_dashboard.go, coralogix/resource_coralogix_dashboard_test.go
Upgrade json-parsing deprecated package
=> Upgrade json deprecated package

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go
Adding validation for time_window in standard alert - required with more_than/less_than
=> Adding validation for time_window in standard alert

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, coralogix/resource_coralogix_logs2metric.go, docs/data-sources/alert.md, docs/resources/alert.md, docs/resources/logs2metric.md, examples/alert/main.tf
Adding length limitation (MaxItems:1) for scheduling time-frames.
Adding updating phase for every alert-type test.
=> Limiting time-frames length and adding updating phase for alert tests

coralogix/resource_coralogix_recording_rules_group.go
Adding validation for recording_rule_group's yaml_content
=> Adding recording_rule_group yaml validation

CHANGELOG.md
patch - adding changelog comment
=> patch - adding changelog comment

CHANGELOG.md, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, docs/resources/alert.md, examples/alert/main.tf
Tracing alert `equals` filter bug-fixing.
=> patch - tracing-alert equals filter bug-fixing

coralogix/provider.go, coralogix/resource_coralogix_alert_test.go
`"USA2":    "ng-api-grpc.cx498.coralogix.com:443"`
=> patch - adding us2 region

CHANGELOG.md, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, docs/data-sources/alert.md, docs/resources/alert.md, examples/alert/main.tf
e.g. -
```hcl
flow {
stage {
...
}
group_by = ["coralogix.metadata.sdkId"]
}
```
=> patch - adding group_by for flow-alerts

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, examples/alert/main.tf
```
...
```
```release-note
...
```
=> fixing flow alert test

docs/data-sources/slo.md, docs/resources/slo.md
This PR adds basic descriptions for SLO, to address ticket https://coralogix.atlassian.net/browse/PLTD-520.
We will need to add additional descriptions for all the other data sources/resources in the future. Also maybe improve examples. If this is OK, I will send a more elaborate PR in the future.
=> SLO Descriptions

CHANGELOG.md, coralogix/resource_coralogix_dashboard.go, examples/dashboard/main.tf, go.mod, go.sum
- [V] Have you added an acceptance test for the functionality being added?
- [V] Have you run the acceptance tests on this branch?
```
...
```
```release-note
...
```
=> patch - fixing flatten of json_content field bug

CHANGELOG.md, coralogix/resource_coralogix_sli.go, coralogix/resource_coralogix_sli_test.go
- [V] Have you added an acceptance test for the functionality being added?
- [V] Have you run the acceptance tests on this branch?
```
...
```
```release-note
...
```
=> minor -  `coralogix_sli.filters` was changed from `TypeList` to `TypeSet`

CHANGELOG.md, coralogix/resource_coralogix_slo.go, docs/data-sources/slo.md, docs/resources/slo.md
```
...
```
```release-note
...
```
=> patch - slo symbol_type bug fixing

coralogix/resource_coralogix_dashboard.go, docs/data-sources/dashboard.md, docs/resources/dashboard.md
```
...
```
```release-note
...
```
=> patch - adding data_mode_type for data_table

CHANGELOG.md, coralogix/resource_coralogix_dashboard.go
Adding a dashboard schema upgrader v1 to v2
=> patch - adding dashboard schema upgrader

CHANGELOG.md, coralogix/resource_coralogix_dashboard.go, docs/resources/dashboard.md
Replace the dashboard in a case it was deleted outside of terraform.
```
...
```
```release-note
...
```
=> Replace in case of not found

CHANGELOG.md, coralogix/resource_coralogix_alert_test.go, coralogix/resource_coralogix_dashboard.go, docs/data-sources/dashboard.md, docs/resources/dashboard.md
```
...
```
```release-note
...
```
=> patch - update line_chart units

coralogix/resource_coralogix_dashboard.go
```
...
```
```release-note
...
```
=> patch - removing jsondiff check when parsing dashboard

.github/workflows/release.yml, CHANGELOG.md, coralogix/resource_coralogix_alert.go, docs/resources/alert.md
```
...
```
```release-note
...
```
=> patch - adding 5Min option to time_window for unique_count

.github/workflows/release.yml, .goreleaser.yaml
```
...
```
```release-note
...
```
=> goreleaser changes

docs/resources/custom_role.md
```
...
```
```release-note
...
```
=> Update documentation for custom role

CHANGELOG.md, coralogix/resource_coralogix_dashboard.go, docs/resources/dashboard.md
```
...
```
```release-note
...
```
=> Dashboards - changing pie_chart and horizontal_bar_chart group-names to optional

coralogix/clientset/grpc/integrations/audit_log.pb.go
I fixed a field number conflict in the generated proto files, which broke the entire provider.
=> Change field number in audit logs proto file

CHANGELOG.md, docs/index.md
```
...
```
```release-note
...
```
=> docs: index + changelog updated

CHANGELOG.md
Add changelog entry for MS Teams Workflow Webhook
=> Add changelong entry for MS Teams Workflow webhook

coralogix/resource_coralogix_group.go, examples/group/main.tf
Make scope id in group resource computed
=> Make scope id in group resource computed

examples/webhook/main.tf
```
...
```
```release-note
...
```
=> Fix webhook example

coralogix/resource_coralogix_dashboard_test.go
Change dashboard test json path
=> Change dashboard test json path

docs/data-sources/action.md, docs/data-sources/alert.md, docs/data-sources/dashboard.md, docs/data-sources/rules_group.md, docs/data-sources/slo.md, docs/data-sources/tco_policies_logs.md, docs/data-sources/webhook.md, docs/index.md, docs/resources/action.md, docs/resources/alert.md, docs/resources/dashboard.md, docs/resources/enrichment.md, docs/resources/rules_group.md, docs/resources/slo.md, docs/resources/tco_policies_logs.md, docs/resources/webhook.md, examples/resources/coralogix_enrichment/resource.tf
```
...
```
```release-note
...
```
=> Fix coralogix_data_set location in coralogix_enrichment

coralogix/resource_coralogix_webhook.go, main.go
Updating documentation of AWS EventBus / EventBridge webhook
=> [PLTD-992] Improving AWS EventBridge webhook documentation

coralogix/resource_coralogix_dashboard.go, coralogix/resource_coralogix_dashboard_test.go, coralogix/resource_coralogix_webhook.go, examples/resources/coralogix_dashboard/dashboard_with_var_path.json
Do not prevalidate dashboard json if its value is unknown.
=> Do not prevalidate dashboard json if its value is unknown

coralogix/resource_coralogix_slo.go, coralogix/resource_coralogix_slo_test.go
```
...
```
```release-note
...
```
=> fixing slo validation bug

coralogix/clientset/callPropertiesCreator.go
```
...
```
```release-note
...
```
=> chore: add analytics headers to 1.18

CHANGELOG.md, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go
```
...
```
```release-note
...
```
=> Fix: added phantom mode

coralogix/resource_coralogix_integration_test.go, docs/resources/dashboard.md
```
...
```
```release-note
...
```
=> Docs example update

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, coralogix/utils/utils.go
```
...
```
```release-note
...
```
=> feat: custom_evaluation_delay

coralogix/resource_coralogix_archive_logs.go, coralogix/resource_coralogix_recording_rules_groups_set.go
```
...
```
```release-note
...
```
=> Fix: Invalid empty region for archive_logs

coralogix/resource_coralogix_recording_rules_groups_set.go, docs/data-sources/recording_rules_groups_set.md, docs/resources/recording_rules_groups_set.md
```
...
```
```release-note
...
```
=> Fix: Recording Rules Attributes Error

coralogix/resource_coralogix_recording_rules_groups_set.go
```
...
```
```release-note
...
```
=> remove validation for RuleGroupSet length

coralogix/dashboard_widgets/schema.go, coralogix/resource_coralogix_dashboard.go, coralogix/utils/utils.go, docs/guides/generating-terraform.md, docs/resources/dashboard.md
```
...
```
```release-note
...
```
=> Fix: Docs and other updates

coralogix/clientset/version.go, go.mod, go.sum
```
...
```
```release-note
...
```
=> chore: update SDK version, prepare release

CHANGELOG.md, coralogix/clientset/version.go, coralogix/resource_coralogix_recording_rules_groups_set.go, docs/data-sources/recording_rules_groups_set.md, docs/guides/generating-terraform.md, docs/resources/recording_rules_groups_set.md
```
...
```
```release-note
...
```
=> Release Prep & Docs updates

coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go
```
...
```
```release-note
...
```
=> fix: override now defaults to top level priority

CHANGELOG.md, coralogix/clientset/version.go, coralogix/resource_coralogix_alert.go, docs/resources/alert.md
```
...
```
```release-note
...
```
=> chore: version update + docs + re-release

CHANGELOG.md, coralogix/resource_coralogix_alert.go
```
...
```
```release-note
...
```
=> fix: update override when priority is updated

coralogix/clientset/version.go
```
...
```
```release-note
...
```
=> chore: version update

docs/guides/alerts-migration-guide.md, docs/guides/generating-terraform.md
```
...
```
```release-note
...
```
=> docs: rm CORALOGIX_DOMAIN mentions

coralogix/provider.go
```
...
```
```release-note
...
```
=> Make CORALOGIX_ENV case insensitive

CHANGELOG.md, coralogix/clientset/grafana-client.go, coralogix/clientset/version.go, coralogix/data_source_hosted_dashboard_test.go, coralogix/resource_grafana_folder.go, coralogix/resource_hosted_dashboard_test.go, go.sum
```
...
```
```release-note
...
```
=> Fix: grafana_folder missing override

CHANGELOG.md, coralogix/clientset/version.go
```
...
```
```release-note
...
```
=> chore: SDK version update + CHANGELOG

CHANGELOG.md, coralogix/clientset/version.go
```
...
```
```release-note
...
```
=> Release 2.0.18

coralogix/resource_coralogix_alert.go, docs/data-sources/alert.md, docs/resources/alert.md
```
...
```
```release-note
...
```
=> adding time_window valid values to docs

CHANGELOG.md, coralogix/clientset/version.go, coralogix/resource_coralogix_preset.go
```
...
```
```release-note
...
```
=> Set payload_type to be computed

scripts/cx-test-resource-cleanup.go
```
...
```
```release-note
...
```
=> chore: Add Notification Center to cleanup job

coralogix/resource_coralogix_alert_test.go, coralogix/resource_coralogix_connector_test.go, coralogix/resource_coralogix_global_router_test.go
```
...
```
```release-note
...
```
=> Move all test notifications to luigis-testing-grounds

CHANGELOG.md, coralogix/clientset/clientset.go, coralogix/clientset/version.go, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, docs/data-sources/alert.md, docs/resources/alert.md, examples/resources/coralogix_alert/resource.tf, go.mod, go.sum
```
...
```
```release-note
...
```
=> Adding support for dynamic duration format for metric alerts time-window

coralogix/clientset/version.go, docs/guides/generating-terraform.md
```
...
```
```release-note
...
```
=> chore: fix asciinema link

CHANGELOG.md, coralogix/resource_coralogix_team.go
```
...
```
```release-note
...
```
=> chore: deprecating teams resource

.github/workflows/acc-test.yml, .github/workflows/build.yml, .github/workflows/cleanup.yml, .github/workflows/release.yml, coralogix/data_source_coralogix_data_set.go, coralogix/data_source_coralogix_enrichment.go, coralogix/data_source_coralogix_rules_group.go, coralogix/resource_coralogix_data_set.go, coralogix/resource_coralogix_enrichment.go, coralogix/resource_coralogix_rules_group.go, coralogix/resource_grafana_folder.go, go.mod
Also Update NC tests to use unique names for resources.
```
...
```
```release-note
...
```
=> Bump go to 1.24

CHANGELOG.md, coralogix/dashboard_widgets/common.go
```
...
```
```release-note
...
```
=> fix: mapping issues with gauge units

CHANGELOG.md, coralogix/alert_schema/v3.go, coralogix/data_source_coralogix_alert_test.go, coralogix/resource_coralogix_alert.go, coralogix/resource_coralogix_alert_test.go, docs/data-sources/alert.md, docs/resources/alert.md
+upgrading schema
+adding test
```
...
```
```release-note
...
```
=> Make notify_on attr in Alert's webhooks_settings as mandatory field:

CHANGELOG.md, coralogix/dashboard_widgets/hexagon.go, coralogix/dashboard_widgets/linechart.go, coralogix/resource_coralogix_dashboard_test.go, docs/data-sources/dashboard.md, docs/data-sources/slo_v2.md, docs/resources/dashboard.md, docs/resources/slo_v2.md
```
...
```
```release-note
...
```
=> Fix: Dataprime queries

coralogix/clientset/version.go
```
...
```
```release-note
...
```
=> version bump

docs/data-sources/alert.md, docs/resources/alert.md, internal/provider/alerts/alert_types/common.go
```
...
```
```release-note
...
```
=> fix: NOT -> INCLUDES
